service: restapi

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-2
  timeout: 10
  memorySize: 256

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'   # 모든 경로에 대해 FastAPI가 처리

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePoetry: false
    dockerizePip: true
    slim: true
    layer: false